### ISSUE TITLE
Issue with program checker - unsure if user error or site error

### ISSUE THREAD

**Issue by SteadyStatus21** [RunestoneInteractive/RunestoneServer#1840]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
Knowing the course will help us a lot
[runestone.academy/ns/books/published/AP_Java_2021/Unit5-Writing-Classes/topic-5-4-accessor-methods.html](runestone.academy/ns/books/published/AP_Java_2021/Unit5-Writing-Classes/topic-5-4-accessor-methods.html)
**What Page were you on**
[runestone.academy/ns/books/published/AP_Java_2021/Unit5-Writing-Classes/topic-5-4-accessor-methods.html](runestone.academy/ns/books/published/AP_Java_2021/Unit5-Writing-Classes/topic-5-4-accessor-methods.html)
**What is your username**
SteadyStatus21
**Describe the bug**
A clear and concise description of what what you were trying to accomplish and what went wrong. Vague statements like X does not work are not helpful. Imagine if one of your students sent you an email that said, "My program doesn't work, whats wrong with it?" Could you help them with only that to go on?
The code compiler and checker seems to be having issues and that it cannot write to a file? Please let me know if this is a user error or a site-wide error. 

Below are as much detail as I can provide, as I am taking this course and I am experiencing alot of errors (that count towards my grade!)

![image](https://user-images.githubusercontent.com/73841304/147857258-f3735795-9e8d-4dee-8f15-87a947883904.png)

Raw text of image above: 
`/usr/local/lib/java/CodeTestHelper.java:24: error: error while writing CodeTestHelper: /usr/local/lib/java/CodeTestHelper.class
public class CodeTestHelper
       ^
./RunestoneTests.java:16: error: cannot find symbol
         changeClass("Pet");
         ^
  symbol:   method changeClass(String)
  location: class RunestoneTests
./RunestoneTests.java:33: error: cannot find symbol
          changeClass("Pet");
          ^
  symbol:   method changeClass(String)
  location: class RunestoneTests
./RunestoneTests.java:47: error: cannot find symbol
          int num = countOccurencesRegex(code, target);
                    ^
  symbol:   method countOccurencesRegex(String,String)
  location: class RunestoneTests
./RunestoneTests.java:69: error: cannot find symbol
          int num = countOccurencesRegex(code, target);
                    ^
  symbol:   method countOccurencesRegex(String,String)
  location: class RunestoneTests
5 errors`

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools
![image](https://user-images.githubusercontent.com/73841304/147857275-aeec3bcc-61db-4b29-ba9c-35eb789d0892.png)
I have no clue what to do here besides upload the inspect element page sorry :(

**Comment by SteadyStatus21** [comment]
I will also mention the following:

I use Windows 10, version 21H2. 
I use a adblocker, installed by my school which is uBlock Origin. 
I have tried disabling my adblock, which does nothing to resolve the issue. 
My school does have GoGuardian along with iBoss, if that affects anything. 

Hope this helps find the issue!

-SteadyStatus21

**Comment by bhoffman0** [comment]
Thanks for reporting this! 
@bnmnetp, could you check the version of the CodeTestHelper.java on line 24 on the new servers. I think the latest should be version 0.3.5 here: https://github.com/bhoffman0/CSAwesome/blob/master/CodeTestHelper.java  (checking with @kmcdonnell2). Maybe an older version that doesn't have these methods is running, because most of the active codes are fine, but it's just these class ones that Kate added special methods for.

**Comment by bnmnetp** [comment]
@bhoffman0 This was the same permissions problem that I fixed a couple days ago.  But I added another server yesterday and did not set the permissions properly on the new one.  This should be resolved as far as I can tell.

It seems bad that we are writing out CodeTestHelper.class in /usr/local/lib/java on our Jobe servers.  Is there a better way to handle this?

**Comment by bnmnetp** [comment]
In any case @SteadyStatus21 You should not get that error anymore.

**Comment by bhoffman0** [comment]
I'm still getting the same errors on Activity: 5.4.2.1 ActiveCode (challenge-5-4-Pet-Class) on https://runestone.academy/ns/books/published/csawesome/Unit5-Writing-Classes/topic-5-4-accessor-methods.html . I think it's the wrong version of CodeTestHelper.java because it's not finding the right methods in it.

**Comment by kmcdonnell2** [comment]
The original tests for 5.4.2 is written with CodeTestHelper 0.3.4, so I
don't think it's a version problem. I also just tested it with 0.3.5 and it
works. :(

**Comment by bnmnetp** [comment]
@kmcdonnell2, @bhoffman0 the new servers I just spun up this weekend had version 0.1.9 !!

I just copied in 0.3.5 to all the new servers and I was able to run all the unit tests on 5.4.2.1 -- They all failed but no compiler errors.

Brad

**Comment by kmcdonnell2** [comment]
Yep, mine works now too!!!

**Comment by bnmnetp** [comment]
Good!!

I'm still working on fine tuning my scripts to keep all of these new servers in sync.  So its good to know that they are working.

**Comment by bhoffman0** [comment]
Works for me now too. Thanks!

**Comment by SteadyStatus21** [comment]
It works now! Thank you!
